# Generated by Django 5.1 on 2026-03-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RenameField(
            model_name="auditlog",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="detail",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="method",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="path",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
