# Generated by Django 5.1 on 2026-03-01 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready for Review"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="ready",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_medical_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="ai_status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
