# Generated by Django 6.0.3 on 2026-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_medicalrecord_doctor_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="ai_confidence_score",
            field=models.IntegerField(
                blank=True, help_text="Real AI generated score (0-100)", null=True
            ),
        ),
    ]
