# Generated by Django 6.0.2 on 2026-03-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="chat_media/"),
        ),
    ]
